% Template pour les sujets des animations du FabLab ETOILE

\NeedsTeXFormat{LaTeX2e}

\ProvidesPackage{monextension}[Extension FabLab, V1.0]

% extensions

\LoadClass[a4paper,10pt]{report}
\RequirePackage[utf8]{inputenc}
\RequirePackage{graphicx}
\RequirePackage{textcomp}
\RequirePackage[french]{babel}
\RequirePackage{hyperref}
\RequirePackage{minted}
\RequirePackage{hyperref}


% commandes personnelles

%\newcommand{}{}
